---
output: html_document
---

<!-- The following script makes it possible to use the mhchem -->
<!-- latex package in a .Rmd file and to knit it into an .html file -->

```{=html}
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: {
    extensions: ["[Contrib]/mhchem/mhchem.js"]
}
});
</script>
```

<!-- place introduction here -->

The extraction of a compound from a solid matrix is affected by a variety of variables: the choice of solvent, the solvent's temperature, the ratio of the solid--to--solvent, and the extraction time. We call these variables factors and their specific values factor levels, and we call the property we measure the response.

#### Response Surface

The two plots on the right are examples of response surfaces. The *x*-axis and the *y*-axis show a range of levels for two factors with the response displayed on the *z*-axis. For the response surface on the upper right, the extraction yield decreases for both high and low levels of the factors, but increases for intermediate levels of the factors, reaching a maximum response in the center of the response surface's boundaries. Although not shown here, reversing these trends simply flips the response surface, which reaches a minimum for intermediate values of the two factors.

The response surface on the lower right is a saddle surface, which occurs when there is an interaction between the two factors. In this case the response has its greatest value when both factors are at their high levels or their low levels, and has its smallest value when one factor's level is high and the other factor's level is low.

#### Mathematical Model of Response Surface

We can model both response surfaces using a full second-order polynomial equation

$$z_i = \beta_0 + \beta_1 x_i + \beta_2 y_i + \beta_{11} (x_i)^2 + \beta_{22} (y_i)^2 + \beta_{12} x_i y_i + r_i$$

where *z* is the response, and *x* and *y* are the levels for the two factors. The subscript *i* designates the *i*^th^ combination of factor levels for *x* and *y*, and the corresponding response. The six $\beta$ terms are the model's coefficients: $\beta_0$ is the intercept (the value of *z* when $x = 0$ and $y = 0$); $\beta_1$ and $\beta_2$ give the linear relationship between the response and each of the two factors; $\beta_{11}$ and $\beta_{22}$ give the curvature between the response and each of the two factors; $\beta_{12}$ gives the interaction between the two factors; and $r_i$ is the residual error, the difference between the model's prediction of $z_i$ and its actual value.
